title:              "The diary of a namad"
tagline:            "Studying Marketing Programing"
email:              "botanica209@gmail.com"
description:        "마케팅/프로그래밍/ 등 새로 배운 것들을 기록하는 공간입니다."
author:             "YR"
baseurl:            "/"
url:                "https://YURA.github.io"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
